### ISSUE TITLE
Memory size exhausted error

### ISSUE THREAD

**Issue by gilbertocarcano** [Garciat/libvorbis.js#2]
Hi,
I'm using your library (thank you for your work!) in a project of mine.
I need to repeat the sequence Init/Encode/Finish once for each phrases in a recording loop.
All works fine until a memory error arises:  Uncaught RangeError: Invalid array buffer length.
The error is in the enlargeMemory function. It doesn't depend on the number of time the sequence is repeated (sometime after 10 encodings, sometime after 15) but it looks like an unfreed memory problem. Is there a way to completely reset the runtime or another work-around to solve this problem?

**Comment by gilbertocarcano** [comment]
Hi,
I found a very ugly workaround but I don't have installed emscripten yet, so I can't hack any c file.
I modified the javascript as below:
1) First I created a Vorbis.dispose() method that frees the state:

     dispose: function(state) {
        Module._free(state);
     }

   but it isn't enough to free the state->encoded_buffer;

2) Then I tried to hack directly the function _lexy_encoder_start:

     var oldBuffer=null;
     function _lexy_encoder_start($sample_rate,$vbr_quality) {
     .
     .
     . 
     if(!oldBuffer)
    {
       $5 = (__Znaj(3145728)|0); // 3 * 1024 * 1024
       oldBuffer=$5;
     }  else
           $5 = oldBuffer;

and this works!

Please let me know if there is a better way.
Thank you very much!

**Comment by Garciat** [comment]
I will look into it. Thank you.

**Comment by Garciat** [comment]
I just rewrote the library wrapper (c914284b4aab97a61ace62eb1dbe0057c1c8d490). Is the bug still present?

**Comment by Garciat** [comment]
Oh, my bad. I'll make a new downloadable release with the changes.
