### ISSUE TITLE
Add `version` to `package.json`

### ISSUE THREAD

**Issue by obrodnikov-amplify** [Garciat/libvorbis.js#3]
It would be great to have a `version` field in `package.json`, so that this package could actually be installed with npm.
Currently, if I try the following dependency: 

```
"dependencies": {
"package": "git://github.com/Garciat/libvorbis.js"
}
```

`npm install` fails with `No version provided in package.json`

**Comment by Garciat** [comment]
I've added a `package.json` to the **[distribution repo](https://github.com/Garciat/libvorbis.js-dist)**. I've also published [the package on npm](https://www.npmjs.com/package/libvorbis.js).

However:

The library was designed with only the browser in mind.

npm users will get a limited API described by [vorbis_encoder.d.ts](https://github.com/Garciat/libvorbis.js/blob/master/src/vorbis_encoder.d.ts). The module exports an instance of `VorbisEncoderModule`.

See [this script](https://github.com/Garciat/libvorbis.js/blob/master/bench/program.js) for instructions on how to use the raw module API.

May I ask:

How do you plan to integrate/use the library? Maybe I could look into improving your use case.
