### ISSUE TITLE
Problem during encoding

### ISSUE THREAD

**Issue by phal0r** [Garciat/libvorbis.js#5]
Hi @Garciat,

thanks for the port. I am trying to use it to encode recordings, but I get this error from time to time:

uncaught exception: abort() at jsStackTrace@https://127.0.0.1:8004/frontend/68535fee4b373eebdfb5.worker.js:1781:14
stackTrace@https://127.0.0.1:8004/frontend/68535fee4b373eebdfb5.worker.js:1798:23
abort@https://127.0.0.1:8004/frontend/68535fee4b373eebdfb5.worker.js:35233:45
_abort@https://127.0.0.1:8004/frontend/68535fee4b373eebdfb5.worker.js:2478:8
_realloc@https://127.0.0.1:8004/frontend/68535fee4b373eebdfb5.worker.js:33073:4
_vorbis_analysis_blockout@https://127.0.0.1:8004/frontend/68535fee4b373eebdfb5.worker.js:4532:11
_encoder_encode_work@https://127.0.0.1:8004/frontend/68535fee4b373eebdfb5.worker.js:28581:9
_encoder_encode@https://127.0.0.1:8004/frontend/68535fee4b373eebdfb5.worker.js:28545:3
makeVorbisEncoderModule/asm._encoder_encode@https://127.0.0.1:8004/frontend/68535fee4b373eebdfb5.worker.js:34770:9
VorbisWorkerScript</VorbisWorkerScript.main/<@https://127.0.0.1:8004/frontend/68535fee4b373eebdfb5.worker.js:576:22

Did you ever experience this or have an idea how to dig into it?

Thanks in advance

**Comment by Garciat** [comment]
I would have to know a bit more about your usage, but my best guess would be that you're trying to encode a chunk that is too big for the limited asm.js memory space (based on the fact that the `realloc` call is failing).

**Comment by phal0r** [comment]
Getting an audio stream via getUserMedia and using the lib like described in the examples. There is one difference... I don't want to throw the worker away after every recording, but I don't think it's the root cause, since this also happens on first recording. 

I don't know, how I can go on from here, so if you need specific information, I will provide it and be glad if we can figure out, what's going wrong :)

**Comment by Garciat** [comment]
Are you using the `VorbisEncoder` class or the `VorbisMediaRecorder` class? Either way, once `VorbisEncoder.finish` has been called, all the encoder state is destroyed. Then, the encoder cannot be reused unless `VorbisEncoder.init` is called again. However, I have not tested this behavior. I would suggest creating new a new instance of the encoder for each 'encoding session' (one `init()`, many `encode()`, one `finish()`).

**Comment by Garciat** [comment]
Please reopen if your issue is not fixed yet. Thanks.
