### ISSUE TITLE
config options to pass to `VorbisMediaRecorder` ?

### ISSUE THREAD

**Issue by kmonsoor** [Garciat/libvorbis.js#9]
hello,

i am using your demo project to apply it on one of mine. While the recording is working, but the output file too small. e.g. 45KB for a 7-min recording.
i've tried both passing and not passing  `audioBitsPerSecond` option while init `VorbisMediaRecorder`.

i am wondering what else the options could be. As the `libvorbis.min.js` is already minified, i am being unable to look it up myself.

would you please give me some pointers ?

**Comment by kmonsoor** [comment]
okay, i think i got it from the README. it 

> implements the W3C MediaRecorder interface

so, this will be the reference: https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder

**Comment by Garciat** [comment]
If the class fails to meet those or you own requirements, please keep me posted. Thanks.
